# Generated by Django 3.0.3 on 2020-03-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_auto_20200308_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='academic_year',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='professor_code',
            new_name='professor_id',
        ),
    ]
