# Generated by Django 3.0.3 on 2020-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0003_auto_20200308_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='taught_by',
        ),
        migrations.AddField(
            model_name='module',
            name='taught_by',
            field=models.ManyToManyField(to='ratingapp.Professor'),
        ),
    ]
