# Generated by Django 2.1.14 on 2020-03-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0007_auto_20200311_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='by_user',
        ),
    ]
