# Generated by Django 2.1.14 on 2020-03-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0006_auto_20200310_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='which_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratingapp.Module'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='which_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratingapp.Professor'),
        ),
    ]
